---
format:
  pdf:
    tbl-cap-location: top
    dpi: 500
    fig-pos: "H"
    number-sections: true
    cite-method: natbib
    include-in-header: 
      - text: |
          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
          \usepackage{rotating}
          \newcommand{\bsideways}{\begin{sidewaystable}[htbp]}
          \newcommand{\esideways}{\end{sidewaystable}}
      - file: preamble.tex 
    include-before-body: title.tex
    keep-tex: TRUE
    fig-format: png
    default-image-extension: png
  docx:
    reference-doc: new_template_no_numbering.docx
pdf-engine: lualatex
# monofont: "DejaVu Sans Mono"
# mainfont: "Times New Roman"
execute: 
  echo: false
  warning: false
editor: source
bibliography: references.bib
biblio-style: apalike
natbiboptions: round
link-citations: true
linkcolor: blue!000!black
urlcolor: blue!000!black
citecolor: blue!000!black
linestretch: 1.5
indent: TRUE
title-block-banner: false
title-block-style: none
---


```{r setup}
#| include=FALSE
options(scipen=999)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      dpi = 500, 
                      fig.pos = "H", 
                      fig.env= 'figure', 
                      tab.topcaption = TRUE,
                      ft.align = "left",
                      ft.arraystretch = 0.5,
                      fig.height = 4,
                      fig.width = 7
                      )
library(tidyverse)
library(readr)
library(readxl)
library(zoo)
library(magick)
library(stringi)
library(patchwork)
library(xtable)
library(scales)
library(rvest)
library(rebus)
library(PNWColors)
library(lubridate)
library(here)
library(flextable)
library(gt)
library(officer)
library(officedown)
library(modelsummary)
library(sandwich)
library(lmtest)

set_flextable_defaults(
  font.size = 7,
  digits = 2,
  font.family = "Arial",
  border.color = "black",
  border.width = 0.5,
  fp_border = fp_border(color = "black", width = 0.5, style = "solid")
)


```

```{r functions}
source(here("Functions","flextable_word.R" ))
source(here("Functions","modelsummary_word.R" ))
source(here("Functions","modelplot_word.R" ))
source(here("Functions","borderlines.R" ))
```

# Introduction

@fornero2011effect 

# Literature review

# Data and methodology

```{r}
#| label: tbl-descriptives
#| tbl-cap: "Descriptive statistics"
#| ft.arraystretch: 0.4


descriptives_table <- 
  read_rds(here("Outputs", "artifacts_descriptive_statistics.rds")) |> 
  pluck(1) |>
   mutate(
    credit_category = str_replace_all(credit_category, "pop", "Population"),
    credit_category = str_replace_all(credit_category, "temp", "Temperature"),
    credit_category = str_replace_all(credit_category, "precip", "Precipitation")
  ) |>
  filter(!str_detect(credit_category, "value")) |> 
  mutate(group = factor(
    case_when(
      credit_category %in% c(
        "central_bank_information", "forward_guidance",
        "miyajima_surprise", "romer_surprise", "target",
        "country_risk"
      ) ~ "Monetary Policy",
      str_starts(credit_category, "corporate") ~ "Corporate Credit",
      str_starts(credit_category, "household") ~ "Household Credit",
      str_starts(credit_category, "land_") |
        str_starts(credit_category, "pop_") ~ "Climate"
    ),
    levels = c("Monetary Policy", "Corporate Credit", "Household Credit", "Climate")
  )) |>
  arrange(group, credit_category) |>
  mutate(credit_category = credit_category |> str_replace_all("_", " ") |> str_to_title()) |> 
  as_grouped_data(groups = "group") |>
  flextable() |>
  colformat_double(digits = 2) |>
  set_header_labels(group = "", credit_category = "Variable",
                    mean = "Mean", median = "Median", sd = "SD",
                    min = "Min", max = "Max", n = "N") |>
  width(j = "credit_category", width = 1.5) |>
  width(j = c("mean", "median", "sd", "min", "max"), width = 0.65) |>
  width(j = "n", width = 0.5)
  
descriptives_table

```


# Results

# Conclusion

\newpage 
# References {.unnumbered}
::: {#refs}
:::


\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}

\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}

\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}

\newpage

# Appendix

## Data


```{r}
#| label: fig-lending_volume_growth_data
#| fig-cap: "Lending volume growth over time"
#| fig-height: 7
#
lending_volume_growth_gg <- 
  read_rds(here("Outputs", "artifacts_lending_volume.rds")) |> 
  pluck(3)

lending_volume_growth_gg
```


```{r}
#| label: fig-lending_rates_o
#| fig-cap: "Lending rates overtime"
#| fig-height: 7

lending_rates_gg <- read_rds(here("Outputs", "artifacts_lending_rates.rds")) |> 
  pluck(2)

lending_rates_gg
```


```{r}
#| label: fig-climate_shocks_data
#| fig-cap: Climate Shocks Data

climate_shocks_gg <- read_rds(here("Outputs", "artifacts_climate_shocks.rds")) |> 
  pluck(2)

climate_shocks_gg
```


```{r}
#| label: fig-market_based_surprises_data
#| fig-cap: "Market-Based Surprises Data"

market_based_surprises_gg <- read_rds(here("Outputs", "artifacts_market_based_surprises.rds")) |> 
  pluck(2)

market_based_surprises_gg
```

```{r}
#| label: fig-theory_based_surprises_datas
#| fig-cap: "Theory-based surprises data"
#| fig.height: 2

theory_based_surprises_gg <- read_rds(here("Outputs", "artifacts_surprises.rds")) |> 
  pluck(3, 3)

theory_based_surprises_gg
```




